Repository Azure-Samples/azure-spring-boot-samples, pull requests merged in 2022-10, with the labels that each got.

#516 Add sparse checkout for sdk/jdbc
  .github/workflows/codeql-analysis.yml
Labels: azure-spring

#517 Add sparse checkout sdk/jdbc for ci github workflow
  .github/workflows/ci.yml
Labels: bug, azure-spring

#518 Update github workflow with sparse checkout action
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
Labels: azure-spring, client

#527 Update github workflow with sparse checkout action and add sdk/jdbc
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
Labels: azure-spring

#521 Upgrade version to Spring Cloud Azure 6.0.0-beta3
  README.md
  aad/spring-cloud-azure-starter-active-directory-b2c/aad-b2c-resource-server/src/main/java/com/azure/spring/sample/aad/b2c/security/WebSecurityConfiguration.java
  aad/spring-cloud-azure-starter-active-directory-b2c/aad-b2c-web-application/README.md
  aad/spring-cloud-azure-starter-active-directory-b2c/aad-b2c-web-application/pom.xml
  aad/spring-cloud-azure-starter-active-directory-b2c/aad-b2c-web-application/src/main/java/com/azure/spring/sample/aad/b2c/security/WebSecurityConfiguration.java
  aad/spring-cloud-azure-starter-active-directory/aad-resource-server-by-filter-stateless/src/main/java/com/azure/spring/sample/aad/security/AadWebSecurityConfig.java
  aad/spring-cloud-azure-starter-active-directory/aad-resource-server-by-filter/pom.xml
  aad/spring-cloud-azure-starter-active-directory/aad-resource-server-by-filter/src/main/java/com/azure/spring/sample/aad/security/WebSecurityConfig.java
  aad/spring-cloud-azure-starter-active-directory/aad-resource-server-by-filter/src/main/resources/static/App/Scripts/todoListSvc.js
  aad/spring-cloud-azure-starter-active-directory/aad-web-application-and-resource-server/pom.xml
  aad/spring-cloud-azure-starter-active-directory/aad-web-application-and-resource-server/src/main/java/com/azure/spring/sample/aad/security/AadWebApplicationAndResourceServerConfig.java
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server/README.md
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-web-application/pom.xml
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-web-application/src/main/java/com/azure/spring/sample/aad/security/AadWebApplicationConfig.java
  aad/spring-security/servlet/oauth2/client-access-multiple-resource-server/client/src/main/java/com/azure/spring/sample/active/directory/oauth2/servlet/sample03/client/configuration/WebSecurityConfiguration.java
  aad/spring-security/servlet/oauth2/client-access-multiple-resource-server/resource-server-1/src/main/java/com/azure/spring/sample/active/directory/oauth2/servlet/sample03/resource/server1/configuration/WebSecurityConfiguration.java
  aad/spring-security/servlet/oauth2/client-access-multiple-resource-server/resource-server-2/src/main/java/com/azure/spring/sample/active/directory/oauth2/servlet/sample03/resource/server2/configuration/WebSecurityConfiguration.java
  aad/spring-security/servlet/oauth2/client-access-resource-server/client/src/main/java/com/azure/spring/sample/active/directory/oauth2/servlet/sample01/client/configuration/WebSecurityConfiguration.java
  aad/spring-security/servlet/oauth2/client-access-resource-server/resource-server/src/main/java/com/azure/spring/sample/active/directory/oauth2/servlet/sample01/resource/server/configuration/WebSecurityConfiguration.java
  aad/spring-security/servlet/oauth2/login-authenticate-using-private-key-jwt/src/main/java/com/azure/spring/sample/reactive/servlet/oauth2/login/jwt/configuration/WebSecurityConfiguration.java
  aad/spring-security/servlet/oauth2/resource-server-check-permissions-by-claims-in-access-token/client/src/main/java/com/azure/spring/sample/active/directory/oauth2/servlet/sample02/client/configuration/WebSecurityConfiguration.java
  aad/spring-security/servlet/oauth2/resource-server-check-permissions-by-claims-in-access-token/resource-server/src/main/java/com/azure/spring/sample/active/directory/oauth2/servlet/sample02/resource/server/configuration/WebSecurityConfiguration.java
  aad/spring-security/servlet/oauth2/resource-server-support-on-behalf-of-flow/client/src/main/java/com/azure/spring/sample/active/directory/oauth2/servlet/sample04/client/configuration/WebSecurityConfiguration.java
  aad/spring-security/servlet/oauth2/resource-server-support-on-behalf-of-flow/resource-server-1/src/main/java/com/azure/spring/sample/active/directory/oauth2/servlet/sample04/resource/server1/configuration/WebSecurityConfiguration.java
  aad/spring-security/servlet/oauth2/resource-server-support-on-behalf-of-flow/resource-server-2/src/main/java/com/azure/spring/sample/active/directory/oauth2/servlet/sample04/resource/server2/configuration/WebSecurityConfiguration.java
  eventhubs/spring-cloud-azure-starter-eventhubs/eventhubs-client/src/main/java/com/azure/spring/sample/eventhubs/client/EventHubClientApplication.java
  eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder/src/main/java/com/azure/spring/sample/eventhubs/binder/EventHubBinderApplication.java
  eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder/src/main/resources/application.yaml
  pom.xml
  servicebus/spring-cloud-azure-starter-integration-servicebus/multiple-namespaces/terraform/main.tf
  servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-multibinders/terraform/main.tf
Labels: azure-spring
