Repository Azure-Samples/azure-spring-boot-samples, pull requests merged in 2022-04, with the labels that each got.

#270 Update CONTRIBUTING.md for main branch
  CONTRIBUTING.md
  README.md
Labels: azure-spring

#271 Update CONTRIBUTING.md for default branch
  CONTRIBUTING.md
  README.md
Labels: azure-spring

#278 Update scripts in ci.yml github action
  .github/workflows/ci.yml
  .github/workflows/codeql_analysis.yml
  README.md
Labels: azure-spring

#285 Use GitHub action to sync label between azure-sdk-for-java repo and this repo
  .github/workflows/sync-label-from-azsdk-repo.yml
Labels: azure-spring

#281 Enhance Aad samples to keep working correctly.
  aad/spring-cloud-azure-starter-active-directory-b2c/aad-b2c-resource-server/README.md
  aad/spring-cloud-azure-starter-active-directory-b2c/aad-b2c-web-application/README.md
  aad/spring-cloud-azure-starter-active-directory-b2c/aad-b2c-web-application/src/main/resources/application.yml
  aad/spring-cloud-azure-starter-active-directory/aad-resource-server-by-filter/README.md
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/README.md
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server-obo/README.md
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server-obo/docs/image-add-grant-admin-consent.png
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server-obo/docs/image-select-application-permission.png
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server-obo/src/main/java/com/azure/spring/sample/aad/controller/SampleController.java
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server-obo/src/main/resources/application.yml
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server/README.md
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server/src/main/java/com/azure/spring/sample/aad/controller/HomeController.java
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-web-application/README.md
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-web-application/src/main/resources/application.yml
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/run_all.ps1
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/run_all.sh
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/terraform/kill-port.ps1
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/terraform/main.tf
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/terraform/outputs.tf
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/terraform/set_identifier_uris.sh
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/terraform/setup_env.ps1
  aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/terraform/setup_env.sh
Labels: azure-spring, feature-request, client, azure-spring-samples

#307 Update ci workflow to add folder `sdk/aot`
  .github/workflows/ci.yml
  .github/workflows/codeql_analysis.yml
Labels: azure-spring, client
